openapi: 3.0.1
info:
  title: ThreatHawk API (Render)
  version: "0.2.0"
servers:
  - url: https://YOUR_SERVICE.onrender.com
paths:
  /health:
    get:
      summary: Healthcheck
      responses:
        "200": { description: ok }
  /findings:
    get:
      summary: Fetch recent findings
      parameters:
        - in: query
          name: limit
          schema: {type: integer, default: 50, minimum: 1, maximum: 500}
        - in: query
          name: min_severity
          schema: {type: integer, default: 3, minimum: 1, maximum: 5}
        - in: query
          name: site
          schema: {type: string}
      responses:
        "200": { description: array of findings }
  /ban:
    post:
      summary: Request IP ban (manual approval advised)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ip]
              properties:
                ip: {type: string}
                reason: {type: string}
      responses:
        "200": { description: accepted }
  /ingest:
    post:
      summary: Pull logs from provider and analyze
      parameters:
        - in: query
          name: source
          schema: {type: string, enum: [cloudflare]}
          required: true
        - in: query
          name: minutes
          schema: {type: integer, default: 5, minimum: 1, maximum: 15}
      responses:
        "200": { description: Ingestion started }
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
