# render.yaml — ThreatHawk on Render
services:
  - type: web
    name: threathawk
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install --no-cache-dir --upgrade -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3          # <<< pin Python here (avoids Rust build)
      - key: THREATHAWK_API_KEY
        sync: false
      - key: THREATHAWK_FINDINGS_PATH
        value: /tmp/findings.jsonl
      - key: THREATHAWK_BANLIST_PATH
        value: /tmp/banlist.txt
      - key: THREATHAWK_BAN_ENABLED
        value: "true"
      - key: THREATHAWK_ENV
        value: prod
      - key: THREATHAWK_MIN_SEVERITY
        value: "3"
      - key: THREATHAWK_EMA_ALPHA
        value: "0.2"
      - key: THREATHAWK_WINDOW_SECONDS
        value: "60"
      - key: CF_API_TOKEN
        sync: false
      - key: CF_ZONE_ID
        sync: false
