# render.yaml — Infrastructure as Code for ThreatHawk
services:
  - type: web
    name: threathawk
    env: python
    plan: free        # change to 'starter' or higher for production
    region: frankfurt # pick closest to users
    buildCommand: |
      pip install --no-cache-dir --upgrade -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: THREATHAWK_API_KEY
        sync: false
      - key: THREATHAWK_SITE
        sync: false
      - key: THREATHAWK_ENV
        value: prod
      - key: THREATHAWK_FINDINGS_PATH
        value: /tmp/findings.jsonl
      - key: THREATHAWK_BANLIST_PATH
        value: /tmp/banlist.txt
      - key: THREATHAWK_BAN_ENABLED
        value: "true"
      - key: THREATHAWK_MIN_SEVERITY
        value: "3"
      - key: THREATHAWK_EMA_ALPHA
        value: "0.2"
      - key: THREATHAWK_WINDOW_SECONDS
        value: "60"
      - key: CF_API_TOKEN
        sync: false
      - key: CF_ZONE_ID
        sync: false
